### ISSUE TITLE
Better documentation for import of resources with composite identifiers

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-awscc#696]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

Resources can be [imported](https://www.terraform.io/cli/import) using the resource's [primary identifier](https://github.com/aws-cloudformation/cloudformation-resource-schema#resource-semantics).
Usually the format of this identifier is "obvious" but there are some resources whose primary identifier is a composite key.
When the documentation for the resource is generated we should do a better job of calling out the ID's format: https://github.com/hashicorp/terraform-provider-awscc/blob/c5f88170f21cad8e2b91ec4a5f1ac70b60d69718/internal/provider/generators/import-examples/main.go#L83

Relates https://github.com/hashicorp/terraform-provider-awscc/issues/688.

**Comment by patbernard** [comment]
This will help for more than just for composite identifiers.  I came here while running into issues importing `awscc_chatbot_slack_channel_configuration`, as the documentation said to use `resource ID`.  Turns out it was resource ARN I needed to use, but that wasn't obvious. This may be due to me being used to documentation explicitly saying `arn`, `name`, or `id`. But in those cases, the AWS Console also shows `id`.

https://github.com/hashicorp/terraform-provider-awscc/blob/6a490c2caa165e53d84330106221db744e63c556/internal/service/cloudformation/schemas/AWS_Chatbot_SlackChannelConfiguration.json#L80

If the documentation instead of saying `resource ID` said `properties/Arn` (whatever the `primaryIdentifier` is), it may make this clearer.
